services:

  apisix:
    image: apache/apisix:3.9.0-debian
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9180:9180"

  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-centos
    volumes:
    - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - apisix
    ports:
    - "9000:9000"

  etcd:
    image: bitnami/etcd:3.5.13
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"

  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - ./prometheus_conf/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_conf/provisioning:/etc/grafana/provisioning"
      - "./grafana_conf/dashboards:/var/lib/grafana/dashboards"
      - "./grafana_conf/config/grafana.ini:/etc/grafana/grafana.ini"

  httpbin:
    image: kennethreitz/httpbin
  web1:
    image: nginx:1.26.0-alpine
    volumes:
      - ./upstream/web1.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80"
    environment:
      - NGINX_PORT=80
  web2:
    image: nginx:1.26.0-alpine
    volumes:
      - ./upstream/web2.conf:/etc/nginx/nginx.conf
    ports:
      - "9082:80"
    environment:
      - NGINX_PORT=80
