deployment:
  admin:
    admin_key_required: false   # Enable Admin API authentication by default for security.
    allow_admin:
      - 0.0.0.0/0
  etcd:
    host:
      - http://etcd:2397

plugins:
  - http-logger
  - ip-restriction
  - jwt-auth
  - key-auth
  - basic-auth
  - limit-conn
  - limit-count
  - limit-req
  - prometheus
  - serverless-post-function
  - serverless-pre-function
  - zipkin
  - traffic-split
  - azure-functions
  - public-api
  - consumer-restriction
  - loki-logger

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

ext-plugin:
  path_for_test: /tmp/runner.sock
